# Generated by Django 4.2.9 on 2026-01-18 05:41

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0002_medicine_brand_medicine_selling_price_and_more'),
        ('doctors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescription_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('patient_name', models.CharField(max_length=200)),
                ('patient_age', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('patient_gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('patient_address', models.TextField()),
                ('consultation_date', models.DateField()),
                ('complaint', models.TextField(blank=True, help_text='Chief complaint', null=True)),
                ('on_examination', models.TextField(blank=True, help_text='Physical examination findings', null=True)),
                ('provisional_diagnosis', models.TextField(blank=True, help_text='Provisional diagnosis', null=True)),
                ('investigations', models.TextField(blank=True, help_text='Recommended investigations', null=True)),
                ('rx_notes', models.TextField(blank=True, help_text='Additional Rx notes', null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_prescriptions', to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions', to='doctors.doctor')),
            ],
            options={
                'db_table': 'prescriptions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrescriptionMedicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosage', models.CharField(help_text='e.g., 500mg, 1 tablet', max_length=100)),
                ('frequency', models.CharField(help_text='e.g., 1-0-1, Twice daily', max_length=100)),
                ('duration', models.CharField(help_text='e.g., 5 days, 1 week', max_length=100)),
                ('instructions', models.TextField(blank=True, help_text='Special instructions', null=True)),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescription_usages', to='inventory.medicine')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescription_medicines', to='prescriptions.prescription')),
            ],
            options={
                'db_table': 'prescription_medicines',
                'unique_together': {('prescription', 'medicine')},
            },
        ),
        migrations.AddField(
            model_name='prescription',
            name='medicines',
            field=models.ManyToManyField(related_name='prescriptions', through='prescriptions.PrescriptionMedicine', to='inventory.medicine'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions', to='patients.patient'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['prescription_id'], name='prescriptio_prescri_aa4c67_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['consultation_date'], name='prescriptio_consult_78f362_idx'),
        ),
    ]
