# Generated by Django 4.2.9 on 2026-01-31 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='patient_weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Patient weight in kg', max_digits=5, null=True),
        ),
    ]
