# Generated by Django 4.2.9 on 2026-01-18 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patient_height_patient_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='age_years',
            field=models.IntegerField(blank=True, help_text='Age in years (if DOB unknown)', null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
