# Generated by Django 4.2.9 on 2026-01-19 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_patient_age_years_alter_patient_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='age_days',
            field=models.IntegerField(blank=True, help_text='Age in days component', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='age_months',
            field=models.IntegerField(blank=True, help_text='Age in months component', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='case_number',
            field=models.CharField(blank=True, help_text='Manual case number', max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='first_visit_date',
            field=models.DateField(blank=True, help_text='Date of first visit to hospital', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='notes',
            field=models.TextField(blank=True, help_text='General remarks/notes about the patient', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='referred_by',
            field=models.CharField(blank=True, help_text='Doctor/person who referred the patient', max_length=200, null=True),
        ),
    ]
