# Generated by Django 4.2.9 on 2026-01-19 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_patient_age_days_patient_age_months_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='pin_code',
            field=models.CharField(blank=True, help_text='PIN/ZIP code', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='address',
            field=models.TextField(help_text='Street address / Locality'),
        ),
    ]
