# Generated by Django 4.2.9 on 2026-01-19 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_patient_city_patient_pin_code_patient_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='case_number',
            field=models.CharField(blank=True, default=None, help_text='Manual case number', max_length=50, null=True, unique=True),
        ),
    ]
