# Generated by Django 4.2.9 on 2026-01-28 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
        ('patients', '0006_alter_patient_case_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('report_type', models.CharField(choices=[('BLOOD_TEST', 'Blood Test'), ('XRAY', 'X-Ray'), ('MRI', 'MRI Scan'), ('CT_SCAN', 'CT Scan'), ('ULTRASOUND', 'Ultrasound'), ('ECG', 'ECG'), ('PATHOLOGY', 'Pathology'), ('RADIOLOGY', 'Radiology')], max_length=20)),
                ('report_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('REVIEWED', 'Reviewed')], default='PENDING', max_length=20)),
                ('findings', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='doctors.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='patients.patient')),
            ],
            options={
                'db_table': 'reports',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['report_date', 'status'], name='reports_report__04b663_idx'), models.Index(fields=['patient'], name='reports_patient_532c66_idx'), models.Index(fields=['doctor'], name='reports_doctor__460bcb_idx')],
            },
        ),
    ]
