# Generated by Django 4.2.9 on 2026-01-31 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='bio',
            field=models.TextField(blank=True, help_text='Doctor biography/description', null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='Doctor profile photo for prescription', null=True, upload_to='doctors/profiles/'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='signature',
            field=models.ImageField(blank=True, help_text='Doctor signature for prescription', null=True, upload_to='doctors/signatures/'),
        ),
    ]
