# Generated by Django 4.2.9 on 2026-01-31 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_doctor_bio_doctor_profile_image_doctor_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='hindi_name',
            field=models.CharField(blank=True, help_text='Doctor name in Hindi (e.g., डॉ. नाम)', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='specialization_hindi',
            field=models.CharField(blank=True, help_text='Specialization in Hindi', max_length=200, null=True),
        ),
    ]
