# Generated by Django 4.2.7 on 2026-01-31 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('DOCTOR', 'Doctor'), ('STAFF', 'Staff'), ('RECEPTIONIST', 'Receptionist'), ('PHARMACIST', 'Pharmacist'), ('ACCOUNTANT', 'Accountant')], default='STAFF', max_length=20),
        ),
    ]
