# Generated by Django 4.2.9 on 2026-01-31 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('ADMIN', 'Admin'), ('DOCTOR', 'Doctor'), ('STAFF', 'Staff'), ('RECEPTIONIST', 'Receptionist'), ('PHARMACIST', 'Pharmacist'), ('ACCOUNTANT', 'Accountant')], default='STAFF', max_length=20),
        ),
    ]
